name: 'Firebase App Distribution'
description: 'GitHub Action that uploads artifacts to Firebase App Distribution'
author: 'Darius Ungur'
inputs:
  appId:
    description: 'App id can be found on the General Settings page'
    required: true
  serviceCredentials:
    description: 'Google Service Credential'
    required: false
  file:
    description: 'Artifact to upload (.apk or .ipa)'
    required: true
  groups:
    description: 'Distribution groups'
    required: false
  releaseNotes:
    description: 'Release notes visible on release page'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'